force-app/main/default/objects/SQX_Complaint__c/SQX_Complaint__c.object-meta.xml
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COM-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Complaint__c/fields/CQ_Customer_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>CQ_Customer_Contact_Email__c</fullName>
    <label>Customer Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint__c/fields/CQ_SQX_Customer__c.field-meta.xml
<CustomField>
    <fullName>CQ_SQX_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Complaints</relationshipLabel>
    <relationshipName>Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint__c/fields/CQ_Title__c.field-meta.xml
<CustomField>
    <fullName>CQ_Title__c</fullName>
    <label>Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/SQX_Complaint_Feedback__c.object-meta.xml
<CustomObject>
    <label>Complaint Feedback</label>
    <nameField>
        <displayFormat>COF-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compaint Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_SQX_Related_To__c.field-meta.xml
<CustomField>
    <fullName>CQ_SQX_Related_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related To</label>
    <referenceTo>SQX_Complaint__c</referenceTo>
    <relationshipLabel>Compaint Feedbacks</relationshipLabel>
    <relationshipName>Compaint_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CQ_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Customer Success Review</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ComplaintFeedbackServiceTest.cls
@IsTest
public class ComplaintFeedbackServiceTest {
	@IsTest
	static void testRequestFeedback_Sucess(){
		Account acc = new Account(Name = 'Test Account');
		insert acc;

		SQX_Complaint__c complaint = new SQX_Complaint__c(
			CQ_Title__c = 'Test Complaint',
			CQ_Customer_Contact_Email__c = 'test@example.com',
			CQ_SQX_Customer__c = acc.Id	
		);
		insert complaint;

		Test.startTest();
		ComplaintFeedbackService.requestFeedback(complaint.Id);
		Test.stopTest();

		SQX_Complaint_Feedback__c[] feedbacks = [Select Id from SQX_Complaint_Feedback__c where CQ_SQX_Related_To__c = :complaint.Id];
		System.assertEquals(1,feedbacks.size());
	}
	@IsTest
    static void testCheckFeedbackExists_True() {
        Account acc = new Account(Name = 'Check Exists Account');
        insert acc;

        SQX_Complaint__c complaint = new SQX_Complaint__c(
            CQ_Title__c = 'Check Feedback',
            CQ_Customer_Contact_Email__c = 'test@check.com',
            CQ_SQX_Customer__c = acc.Id
        );
        insert complaint;

        SQX_Complaint_Feedback__c feedback = new SQX_Complaint_Feedback__c(
            CQ_SQX_Related_To__c = complaint.Id,
            CQ_Status__c = 'Requested'
        );
        insert feedback;

        Test.startTest();
        Boolean exists = ComplaintFeedbackService.checkFeedbackExists(complaint.Id);
        Test.stopTest();

        System.assertEquals(true, exists, 'Feedback should exist');
    }
}