force-app/main/default/objects/SQX_Complaint__c/SQX_Complaint__c.object-meta.xml
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COM-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Complaint__c/fields/CQ_Customer_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>CQ_Customer_Contact_Email__c</fullName>
    <label>Customer Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint__c/fields/CQ_SQX_Customer__c.field-meta.xml
<CustomField>
    <fullName>CQ_SQX_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Complaints</relationshipLabel>
    <relationshipName>Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint__c/fields/CQ_Title__c.field-meta.xml
<CustomField>
    <fullName>CQ_Title__c</fullName>
    <label>Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/SQX_Complaint_Feedback__c.object-meta.xml
<CustomObject>
    <label>Complaint Feedback</label>
    <nameField>
        <displayFormat>COF-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compaint Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_Comment__c.field-meta.xml
<CustomField>
    <fullName>CQ_Comment__c</fullName>
    <label>Additional Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_SQX_Related_To__c.field-meta.xml
<CustomField>
    <fullName>CQ_SQX_Related_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related To</label>
    <referenceTo>SQX_Complaint__c</referenceTo>
    <relationshipLabel>Compaint Feedbacks</relationshipLabel>
    <relationshipName>Compaint_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CQ_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Customer Success Review</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FeedbackFormServiceTest.cls
@IsTest
public class FeedbackFormServiceTest {
	@IsTest
	static void testSubmitFeedback(){
		Account acc = new Account(Name = 'Test Account');
		insert acc;

		SQX_Complaint__c complaint = new SQX_Complaint__c(
			CQ_Title__c = 'Test Complaint',
			CQ_Customer_Contact_Email__c = 'test@example.com',
			CQ_SQX_Customer__c = acc.Id	
		);
		insert complaint;

		SQX_Complaint_Feedback__c feedback = new SQX_Complaint_Feedback__c(
			CQ_SQX_Related_To__c = complaint.Id,
			CQ_Status__c = 'Requested'
		);
		insert feedback;

		Test.startTest();
		SQX_Complaint_Feedback__c fetched = FeedbackFormService.getFeedbackRecord(feedback.Id);
		FeedbackFormService.submitFeedback(feedback.Id, '2 - Satisfied','Yes','Looks fine.');
		Test.stopTest();

		feedback = [Select CQ_Status__c,CQ_Comment__c from SQX_Complaint_Feedback__c where Id = :feedback.Id];
		System.assertEquals('Customer Success Review', feedback.CQ_Status__c);
		System.assertEquals('Looks fine.', feedback.CQ_Comment__c);
	}
}