force-app/main/default/objects/SQX_Complaint__c/SQX_Complaint__c.object-meta.xml
<CustomObject>
    <label>Complaint</label>
    <nameField>
        <displayFormat>COM-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Complaint__c/fields/CQ_Title__c.field-meta.xml
<CustomField>
    <fullName>CQ_Title__c</fullName>
    <label>Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/SQX_Complaint_Feedback__c.object-meta.xml
<CustomObject>
    <label>Complaint Feedback</label>
    <nameField>
        <displayFormat>COF-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compaint Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_Comment__c.field-meta.xml
<CustomField>
    <fullName>CQ_Comment__c</fullName>
    <label>Additional Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_Experience__c.field-meta.xml
<CustomField>
    <fullName>CQ_Experience__c</fullName>
    <label>Your Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - Highly Unsatisfied</fullName>
            </value>
            <value>
                <fullName>2 - Satisfied</fullName>
            </value>
            <value>
                <fullName>3 - Highly Satisfied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_Issue_Resolved__c.field-meta.xml
<CustomField>
    <fullName>CQ_Issue_Resolved__c</fullName>
    <label>Is the Issue Resolved?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_SQX_Related_To__c.field-meta.xml
<CustomField>
    <fullName>CQ_SQX_Related_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related To</label>
    <referenceTo>SQX_Complaint__c</referenceTo>
    <relationshipLabel>Compaint Feedbacks</relationshipLabel>
    <relationshipName>Compaint_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CQ_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Customer Success Review</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FeedbackFormService.cls
public without sharing class FeedbackFormService {
    @auraEnabled(cacheable=true)
    public static SQX_Complaint_Feedback__c getFeedbackRecord(Id feedbackId){
        SQX_Complaint_Feedback__c feedback = [ Select Id, CQ_SQX_Related_To__c, CQ_Status__c,CQ_SQX_Related_To__r.Name,CQ_SQX_Related_To__r.CQ_Title__c from SQX_Complaint_Feedback__c Where Id =: feedbackId limit 1];
        
        if(feedback.CQ_Status__c != 'Requested'){
            throw new AuraHandledException('Feedback already submitted  or inactive.');
        }
        return feedback;
    }
    @auraEnabled
    public static void submitFeedback(Id feedbackId, String experience, String resolved, String comment) {
        String groupId = [Select Id from Group Where Name = 'Customer Success Team' limit 1].Id;
        SQX_Complaint_Feedback__c feedback = [ Select Id from SQX_Complaint_Feedback__c Where Id =: feedbackId limit 1];
        feedback.CQ_Experience__c = experience;
        feedback.CQ_Issue_Resolved__c = resolved;
        feedback.CQ_Comment__c = comment;
        feedback.CQ_Status__c = 'Customer Success Review';
        feedback.OwnerId = groupId;
        update feedback;
    }
}