force-app/main/default/objects/SQX_Complaint_Feedback__c/SQX_Complaint_Feedback__c.object-meta.xml
<CustomObject>
    <label>Complaint Feedback</label>
    <nameField>
        <displayFormat>COF-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compaint Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_Issue_Resolved__c.field-meta.xml
<CustomField>
    <fullName>CQ_Issue_Resolved__c</fullName>
    <label>Is the Issue Resolved?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_Status__c.field-meta.xml
<CustomField>
    <fullName>CQ_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Customer Success Review</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CompleteReviewService.cls
/**
 * Service class to handle the completion of customer feedback reviews.
 */
 public with sharing class CompleteReviewService{
    /**
     * Completes the review process for a given feedback record.
     * Updates the feedback status to 'Resolved' and sets the resolution provided by the user.
     *
     * @param feedbackId  The Id of the SQX_Complaint_Feedback__c record to update.
     * @param resolution  The resolution details for the complaint.
     */
    @auraEnabled
    public static void completeReview(Id feedbackId, String resolution) {
        // Validate that resolution text is not blank or null
        if(String.isBlank(resolution)){
            throw new AuraHandledException('Resolution is required.');
        }
        
        // Fetching the feedback record
        SQX_Complaint_Feedback__c feedback = [ Select Id,CQ_Status__c from SQX_Complaint_Feedback__c Where Id =: feedbackId limit 1];
        
        // Ensure the feedback record is in 'Customer Success Review' status before updating
        if(feedback.CQ_Status__c != 'Customer Success Review'){
            throw new AuraHandledException('Feedback is not ready for review.');
        }
        
        // Updating the feedback record with provided details
        feedback.CQ_Issue_Resolved__c = resolution;
        feedback.CQ_Status__c = 'Resolved';
        
        update feedback;
    }
}